create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  preferred_language text default 'es',
  plan text not null default 'free',
  created_at timestamptz not null default now()
);

create table if not exists public.live_sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  code text not null unique,
  source_language text not null,
  status text not null default 'live' check (status in ('live','ended')),
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.session_participants (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  target_language text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.live_captions (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.live_sessions(id) on delete cascade,
  source_text text not null,
  source_language text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.live_sessions enable row level security;
alter table public.session_participants enable row level security;
alter table public.live_captions enable row level security;

create policy "profile self" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "session public read" on public.live_sessions for select using (true);
create policy "session auth create" on public.live_sessions for insert to authenticated with check (auth.uid() = owner_id or owner_id is null);
create policy "session owner update" on public.live_sessions for update to authenticated using (auth.uid() = owner_id or owner_id is null);
create policy "participants public insert" on public.session_participants for insert with check (true);
create policy "participants public read" on public.session_participants for select using (true);
create policy "captions public read" on public.live_captions for select using (true);
create policy "captions auth insert" on public.live_captions for insert to authenticated with check (true);

alter publication supabase_realtime add table public.session_participants;
alter publication supabase_realtime add table public.live_captions;
